version: "3.5"

services:

  react-dev:
    container_name: 'frontend_container'
    build:
      context: ./ta_frontend
      dockerfile: Dockerfile
    volumes:
      - './ta_frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  postgres:
    image: 'postgres:11'
    container_name: 'postgres_container'
    ports:
      - '54320:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'pgadmin_container'
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres

  backend:
    container_name: 'backend-container'
    restart: always
    build: ./ta_backend
    ports:
      - "5000:5000"
    volumes:
      - ./ta_backend:/usr/src/app
volumes:
  postgres_data: